spring.application.name=tasks 

#Clever Cloud
spring.datasource.url=jdbc:mysql://usq6gdtph4c60uo2:sGvErRKcfIFrF46FZV4t@bhwnyelvlzy86m6tj2gr-mysql.services.clever-cloud.com:3306/bhwnyelvlzy86m6tj2gr
#Local DB
#spring.datasource.url=jdbc:mysql://localhost:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
#spring.datasource.username=nazwa_uzytkownika
#spring.datasource.password=twoje_haslo

trello.api.endpoint.prod=https://api.trello.com/1
trello.app.key=85e0c8687c327eadd86ca942f0cea82c
trello.app.token=ATTA83719da319c02f082e4e2f29def56be16291e8eb1a7518d0abec0d94d21b6d7931CAFBDD
trello.app.username=rafagerus

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# EMAIL CONFIGURATION
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
admin.mail=gerusrafal@gmail.com

app.scheduler.cron=0 0 10 * * *